version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://database:27017/mydb
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - '27017:27017'

